### ISSUE TITLE
[Windows] 現状の自分にとっての GVim8 vs NeoVim

### ISSUE THREAD

**Issue by ghost** [LumaKernel/dotfiles#1]
それぞれの問題点 (もう片方で解決するもの限定)

GVim8
- ぶっちゃけそんなにない
- 久しぶりに vim-airline使ってみたが，powerlineのフォント微妙にズレるね

![image](https://user-images.githubusercontent.com/29811106/71637771-da249f00-2c8f-11ea-8442-7eab1d0c34d8.png)

- フォントとか色々に依存すると思うんだけど，IMEで日本語打ったとき，微妙に微妙

![image](https://user-images.githubusercontent.com/29811106/71637769-ba8d7680-2c8f-11ea-93d2-ed7479354309.png)

NeoVim
- 最新のVimのパッチの対応が追いついてない（まあ特性上，一生追いつきはしないだろうけど）
- 一部プラギンが対応していなかったり，テストされていなかったり，微妙に変な挙動になったり
  - 自分で書いたプラギンも対応してないｗ

**Comment by ghost** [comment]
neovimの思想がわかるかもしれない Shougo さんのインタビュー記事 antedly.com/user/profile/edit

**Comment by LumaKernel** [comment]
GVimはつかわなくなった。

- guitermcolors 便利
- NeoVim でうごくプラグインをつかいたい/つくりたい
- Vim で NeoVim 向けのプラグイン動くようにするのちょっとめんどそう

ただ、自分でビルドは一度してみたい
