### ISSUE TITLE
[Vim] devicons.vim は使わない

### ISSUE THREAD

**Issue by ghost** [LumaKernel/dotfiles#2]
1. 重い
2. それ自体に色をつける能力があるはずなのに，追加でプラギンが必要であまり整っている感じがしない
3. やっぱそんなにいらない．かっこいいけど
4. そのプラギンのリポジトリで完結してなくて，vim-airline側によくわからんファイル作られた
  `autoload\airline\extensions\tabline\formatters\webdevicons.vim`
  まあ airline 側がよしなのかもしれないけど，プラギンマネージャー使ってそういう挙動されると困る

lightweight だっていうから airline やってみようみたいなところがあったので，重いしいいかな…と

NERDTree側の

```
  let g:NERDTreeDirArrowExpandable="\uf114"
  let g:NERDTreeDirArrowCollapsible="\uf115"
```

の設定で十分

**Comment by ghost** [comment]
そもそも NERDTreeを使うのをやめてしまった
devicons.vim使ってる人多いかも． 4. が気になるなあ

**Comment by ghost** [comment]
4. ，airline側だったら風評被害で申し訳ない

**Comment by LumaKernel** [comment]
おk
