### ISSUE TITLE
[Windows] そもそもなぜ MSYS2 を使うのか考える

### ISSUE THREAD

**Issue by ghost** [LumaKernel/dotfiles#4]
## MSYS2を使うことの問題点

- Windowsの実行バイナリとそんなに親和性がいいわけではない
  - vim,nvim,pythonうまく動かず双方に環境が必要
- pythonはさらにめんどくさくて，MSYS2内で用意しなければいけないが，
  `mingw-w64-i686-python3` は gcc に使われているとかなんとか，依存関係のアレ
  で消すことができない
- これのためのめんどくさい調整が，めんどくさい
- `pacman` が，使いづらい
- Windows やめたい

## MSYS2 の使いみち

- cmdの代わり
  - まいいんじゃないの
  - [解決案] WSL
  - [解決案] PowerShell を使う．Windowsを使う代償だよ…
 

- gcc
  - なんだかんだ欲しくなっていしまう
  - [解決案] 入れるだけ入れて別で使う (別 : Vim内)
  - [解決案] scoop のやつを使う

- git
  - Vimから起動してこっちでごちゃごちゃしたりしてた（これはもうやめよう）
  - それでもなんだかんだ欲しくなりそう
  - [解決案] WSLを使う
  - [解決案] scoop のを使う

- findコマンドなど
  - [解決案] WSL．ぶっちゃけこれでまず困らないと思う

- make
  - これはもう MSYS2 に任せるしか…ないかな
  - そんなに頻繁には使わないだろ

- make test
  - こういうのも Vim 側から実行できてほしいし，うまく調整してくれ

**Comment by ghost** [comment]
## 今の所の結論

- MSYS2に求めすぎない
- 基本的には，Vimでできるようにする．MSYS2 開くのはダサいので卒業しよう
- まあ使いたい時に，そこにあると便利だよね
- で，vimも使えたらそれは嬉しいよね．機能絞っておこう
- でもそのvim は別に最低限でいいよね，本格的なのほしいんならGUIで起動して

**Comment by ghost** [comment]
Vimで開くターミナルってあれなんなんだろうね．そこらへんの環境をつくることと，それがなんなのかを知ることが重要そうだ，はい

**Comment by LumaKernel** [comment]
使うのをやめた

**Comment by LumaKernel** [comment]
git bash は使い始めた。メインではなく、欲しくなったら使うよ程度

cf: https://github.com/LumaKernel/dotfiles/issues/8
