### ISSUE TITLE
[Vim] 補完系のプラグインが何をしているかわからない

### ISSUE THREAD

**Issue by ghost** [LumaKernel/dotfiles#5]
`neocomplete` から `deoplete` に変えようと思ったが，そもそも何をしてるかわからないため知ろう

## デフォルト

単語補完はできる

## オムニ補完ってなんなの

わからん

**Comment by ghost** [comment]
まじでわからん

**Comment by LumaKernel** [comment]
なんかとりあえずvimデフォルトの omnifunc をうまく使うってのが基本パターンっぽい気がする。それの自動設定までやるかそこは自分でやるか、みたいな流儀はあるとして
